# Generated by Django 4.1 on 2023-11-27 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Members", new_name="Member",),
    ]
